/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "",
    "aws_appsync_graphqlEndpoint": "",
    "aws_appsync_region": "",
    "aws_appsync_authenticationType": "",
    "aws_appsync_apiKey": ""
};


export default awsmobile;
