/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql-codegen
 *
 * for this file to be re-created
 */

import * as Types from '../app/services/types.generated';

import { api } from './../app/TaskApi';
// module.hot?.accept();
export type CreateTaskMutationVariables = Types.Exact<{
  input: Types.CreateTaskInput;
}>;


export type CreateTaskMutation = { __typename?: 'Mutation', createTask?: { __typename: 'Task', id: string, title: string, description?: string } };


export const CreateTaskDocument = `
    mutation CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    id
    title
    description
    __typename
  }
}
    `;

const injectedRtkApi = api.injectEndpoints({
  // overrideExisting: module.hot?.status() === "apply",
  endpoints: (build) => ({
    CreateTask: build.mutation<CreateTaskMutation, CreateTaskMutationVariables>({
      query: (variables) => ({ document: CreateTaskDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { useCreateTaskMutation } = injectedRtkApi;

